[package]
name = "rr-backend"
version = "0.1.0"
edition = "2024"
authors = [ "neeleshpoli <72574589+neeleshpoli@users.noreply.github.com>" ]
publish = false

[package.metadata.release]
release = false

# # https://github.com/rustwasm/wasm-pack/issues/1247
# [package.metadata.wasm-pack.profile.release]
# wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6.0", features = ['d1'] }
worker-macros = "0.5.0"
console_error_panic_hook = { version = "0.1.7" }
models = { git = "https://github.com/Rayalaseema-Ruchulu/models.git", version = "0.1.0" }
serde = "1.0.219"
