name: Deploy Worker
on:
  push:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      
      - run: rustup -v target add wasm32-unknown-unknown --toolchain stable && cargo install wasm-pack

      # Setup flutter for web builds
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get Flutter dependencies
        working-directory: ./public/frontend
        run: |
          flutter pub get

      - name: Build Flutter Web App
        working-directory: ./public/frontend
        run: |
          flutter build web --wasm --release --pwa-strategy=none

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "latest"
          workingDirectory: "public"
