name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4
      - run: rustup -v target add wasm32-unknown-unknown --toolchain stable && cargo install wasm-pack

      # Setup flutter for web builds
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with: 
          channel: 
            
      - name: Ensure flutter web is built
        run: cd public/flutter && flutter build web --wasm --release
      
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "latest"
          workingDirectory: "public"
